// Code generated by Prismic. DO NOT EDIT.

import Callout from "./Callout";
import ComparisonTable from "./ComparisonTable";
import Gallery from "./Gallery";
import ImageBlock from "./ImageBlock";
import NewsletterCta from "./NewsletterCta";
import ProsCons from "./ProsCons";
import PullQuote from "./PullQuote";
import RankingList from "./RankingList";
import RelatedArticles from "./RelatedArticles";
import RichText from "./RichText";
import VideoEmbed from "./VideoEmbed";

export const components = {
	callout: Callout,
	comparison_table: ComparisonTable,
	gallery: Gallery,
	image_block: ImageBlock,
	newsletter_cta: NewsletterCta,
	pros_cons: ProsCons,
	pull_quote: PullQuote,
	ranking_list: RankingList,
	related_articles: RelatedArticles,
	rich_text: RichText,
	video_embed: VideoEmbed
};