export type Article = {
  slug: string;
  title: string;
  excerpt: string;
  coverImageUrl: string;
  category: "noticias" | "reviews" | "top-lista";
  gameSlug: string;
  author: string;
  breaking: boolean;
  publishedAt: string;
  readingMinutes: number;
  reviewScore?: number;
  tags: string[];
};

export type Game = {
  slug: string;
  title: string;
  developer: string;
  releaseDate: string;
  platforms: string[];
  summary: string;
};

export const ARTICLES: Article[] = [
  {
    slug: "cities-skylines-2-analise-completa",
    title: "Cities: Skylines II — A Simulação Urbana Que Nenhuma Outra Consegue Alcançar",
    excerpt: "A Colossal Order entregou um salto geracional. Tráfego inteligente, economia dinâmica e uma profundidade de zoneamento que vai consumir centenas de horas sem que você perceba.",
    coverImageUrl: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=1400&h=700&fit=crop&auto=format",
    category: "reviews",
    gameSlug: "cities-skylines-2",
    author: "Rafael Moura",
    breaking: false,
    publishedAt: "24 Jul 2026",
    readingMinutes: 12,
    reviewScore: 9.2,
    tags: ["simulação", "gestão", "cidades", "pc"],
  },
  {
    slug: "europa-universalis-v-sistema-diplomatico",
    title: "Europa Universalis V revela sistema diplomático completamente refeito com nós de influência",
    excerpt: "A Paradox Interactive detalhou em livestream o novo sistema de relações exteriores, que substitui os pontos de prestígio por uma rede de influência dinâmica entre nações.",
    coverImageUrl: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=600&h=340&fit=crop&auto=format",
    category: "noticias",
    gameSlug: "europa-universalis-v",
    author: "Camila Fonseca",
    breaking: true,
    publishedAt: "24 Jul 2026",
    readingMinutes: 4,
    tags: ["paradox", "estratégia", "dlc"],
  },
  {
    slug: "civilization-vii-preview-eras",
    title: "Civilization VII: Eras Descartáveis — Jogamos 6 Horas e Temos Muito a Dizer",
    excerpt: "O sistema de eras que descarta cidades e unidades entre épocas é divisivo, mas há genialidade escondida no caos. Preview completo após sessão presencial com a 2K.",
    coverImageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=340&fit=crop&auto=format",
    category: "noticias",
    gameSlug: "civilization-vii",
    author: "Bruno Lacerda",
    breaking: false,
    publishedAt: "23 Jul 2026",
    readingMinutes: 8,
    tags: ["prévia", "4x", "turn-based"],
  },
  {
    slug: "cities-skylines-2-patch-1-3",
    title: "Patch 1.3 de Cities: Skylines II corrige desempenho e adiciona transporte aquático",
    excerpt: "A atualização resolve stuttering em GPUs NVIDIA e introduz balsas, hidrobarcos e a primeira implementação de canais navegáveis desde o lançamento.",
    coverImageUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=600&h=340&fit=crop&auto=format",
    category: "noticias",
    gameSlug: "cities-skylines-2",
    author: "Letícia Drum",
    breaking: false,
    publishedAt: "23 Jul 2026",
    readingMinutes: 3,
    tags: ["patch", "atualização", "desempenho"],
  },
  {
    slug: "manor-lords-analise",
    title: "Manor Lords — A Joia Medieval em Early Access Que Vale Cada Centavo",
    excerpt: "Uma joia medieval em Early Access que equilibra gestão de aldeia com batalhas táticas de forma surpreendente. O solo interativo e o sistema de abastecimento são brilhantes.",
    coverImageUrl: "https://images.unsplash.com/photo-1599833975787-5c143f373c30?w=400&h=240&fit=crop&auto=format",
    category: "reviews",
    gameSlug: "manor-lords",
    author: "Rafael Moura",
    breaking: false,
    publishedAt: "18 Jul 2026",
    readingMinutes: 10,
    reviewScore: 8.5,
    tags: ["medieval", "gestão", "rts", "early-access"],
  },
  {
    slug: "frostpunk-2-analise",
    title: "Frostpunk 2: O Peso do Poder Que Você Escolheu",
    excerpt: "A 11 bit studios eleva a fórmula do original com dilemas políticos que pesam tanto quanto o frio que ameaça sua cidade. Um dos melhores jogos do ano.",
    coverImageUrl: "https://images.unsplash.com/photo-1491002052546-bf38f186af56?w=400&h=240&fit=crop&auto=format",
    category: "reviews",
    gameSlug: "frostpunk-2",
    author: "Camila Fonseca",
    breaking: false,
    publishedAt: "10 Jul 2026",
    readingMinutes: 11,
    reviewScore: 9.0,
    tags: ["sobrevivência", "simulação", "gestão"],
  },
  {
    slug: "age-of-mythology-retold-analise",
    title: "Age of Mythology: Retold — Nostalgia Bem-Feita, Mas o Tempo Passou",
    excerpt: "Gráficos renovados e QoL de 2024, porém o design de 2004 começa a mostrar suas limitações quando comparado aos RTS modernos. Fãs do original adorarão.",
    coverImageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=240&fit=crop&auto=format",
    category: "reviews",
    gameSlug: "age-of-mythology-retold",
    author: "Bruno Lacerda",
    breaking: false,
    publishedAt: "2 Jul 2026",
    readingMinutes: 9,
    reviewScore: 7.8,
    tags: ["rts", "mitologia", "remake"],
  },
  {
    slug: "victoria-4-anunciado",
    title: "Victoria 4 é Oficialmente Anunciado pela Paradox Interactive",
    excerpt: "A Paradox confirmou o desenvolvimento de Victoria 4 durante o PDX Con 2026. O jogo promete sistema econômico completamente refeito e suporte a partidas multijogador.",
    coverImageUrl: "https://images.unsplash.com/photo-1529417305485-480f579e7578?w=600&h=340&fit=crop&auto=format",
    category: "noticias",
    gameSlug: "victoria-4",
    author: "Bruno Lacerda",
    breaking: true,
    publishedAt: "20 Jul 2026",
    readingMinutes: 5,
    tags: ["paradox", "anúncio", "grand strategy"],
  },
  {
    slug: "top-10-mods-cities-skylines-2",
    title: "Os 10 Mods Essenciais para Cities: Skylines II em 2026",
    excerpt: "Do Traffic Manager renovado ao pacote de assets europeu com 800 edifícios, reunimos os mods que transformam a experiência de construir cidades no simulador da Colossal Order.",
    coverImageUrl: "https://images.unsplash.com/photo-1568659358539-79c6f5375ebe?w=600&h=340&fit=crop&auto=format",
    category: "listas-top",
    gameSlug: "cities-skylines-2",
    author: "Letícia Drum",
    breaking: false,
    publishedAt: "22 Jul 2026",
    readingMinutes: 7,
    tags: ["mods", "top 10", "comunidade"],
  },
  {
    slug: "7-lideres-civilization-vii",
    title: "Os 7 Líderes Mais Poderosos de Civilization VII na Patch 2.1",
    excerpt: "Depois da grande rebalanceada de julho, o meta mudou. Trajan continua forte, mas Amina de Zazzau emergiu como a escolha dominante para vitórias por ciência e cultura.",
    coverImageUrl: "https://images.unsplash.com/photo-1571104508999-893933ded431?w=600&h=340&fit=crop&auto=format",
    category: "listas-top",
    gameSlug: "civilization-vii",
    author: "Rafael Moura",
    breaking: false,
    publishedAt: "20 Jul 2026",
    readingMinutes: 6,
    tags: ["tier list", "meta", "líderes"],
  },
  {
    slug: "5-motivos-jogar-frostpunk-2",
    title: "5 Motivos Para Você Começar a Jogar Frostpunk 2 Agora Mesmo",
    excerpt: "Se você está na dúvida se o jogo é para você, esses cinco pontos vão ajudar a decidir — inclusive se você nunca jogou o primeiro.",
    coverImageUrl: "https://images.unsplash.com/photo-1612178537253-bccd437b730e?w=600&h=340&fit=crop&auto=format",
    category: "listas-top",
    gameSlug: "frostpunk-2",
    author: "Camila Fonseca",
    breaking: false,
    publishedAt: "15 Jul 2026",
    readingMinutes: 5,
    tags: ["recomendação", "top 5", "guia"],
  },
  {
    slug: "eu5-guia-divida",
    title: "Como Dominar o Sistema de Dívida em EU V Sem Entrar em Colapso Econômico",
    excerpt: "Empréstimos, juros compostos e insolvência nacional — guia completo para sobreviver à economia mais complexa que a Paradox já criou.",
    coverImageUrl: "https://images.unsplash.com/photo-1524661135-423995f22d0b?w=600&h=340&fit=crop&auto=format",
    category: "noticias",
    gameSlug: "europa-universalis-v",
    author: "Bruno Lacerda",
    breaking: false,
    publishedAt: "19 Jul 2026",
    readingMinutes: 9,
    tags: ["guia", "economia", "dívida"],
  },
  {
    slug: "manor-lords-2-milhoes",
    title: "Manor Lords Atinge 2 Milhões de Cópias Vendidas em Early Access",
    excerpt: "O game solo de Greg Styczeń se tornou um dos Early Access mais vendidos da história da Steam, superando Palworld em velocidade de crescimento.",
    coverImageUrl: "https://images.unsplash.com/photo-1449824913935-59a10b8d2000?w=600&h=340&fit=crop&auto=format",
    category: "noticias",
    gameSlug: "manor-lords",
    author: "Letícia Drum",
    breaking: false,
    publishedAt: "17 Jul 2026",
    readingMinutes: 3,
    tags: ["steam", "vendas", "early access"],
  },
  {
    slug: "humankind-analise",
    title: "Humankind — Um Rival Sério Para a Civilização, Finalmente",
    excerpt: "Após dois anos de patches, a Amplitude Systems entregou o jogo que o lançamento prometia. O sistema de culturas híbridas agora funciona — e é extraordinário.",
    coverImageUrl: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&h=340&fit=crop&auto=format",
    category: "reviews",
    gameSlug: "humankind",
    author: "Bruno Lacerda",
    breaking: false,
    publishedAt: "5 Jul 2026",
    readingMinutes: 12,
    reviewScore: 8.8,
    tags: ["4x", "civilizações", "turn-based"],
  },
  {
    slug: "top-8-grand-strategy-iniciantes",
    title: "Os 8 Melhores Grand Strategy Para Quem Está Começando",
    excerpt: "Paradox pode assustar, mas existem ótimos jogos de estratégia para todos os níveis. Do mais acessível ao mais profundo — guia para iniciantes.",
    coverImageUrl: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&h=340&fit=crop&auto=format",
    category: "listas-top",
    gameSlug: "europa-universalis-v",
    author: "Letícia Drum",
    breaking: false,
    publishedAt: "12 Jul 2026",
    readingMinutes: 8,
    tags: ["top 8", "iniciantes", "grand strategy"],
  },
];

export const GAMES: Game[] = [
  {
    slug: "cities-skylines-2",
    title: "Cities: Skylines II",
    developer: "Colossal Order",
    releaseDate: "24 Out 2023",
    platforms: ["PC", "PS5", "Xbox Series X"],
    summary: "Simulador de construção de cidades de última geração com economia dinâmica e tráfego realista.",
  },
  {
    slug: "europa-universalis-v",
    title: "Europa Universalis V",
    developer: "Paradox Development Studio",
    releaseDate: "Mar 2027 (previsto)",
    platforms: ["PC", "Mac"],
    summary: "Grand strategy histórico com o mais profundo sistema de diplomacia e economia já criado pela Paradox.",
  },
  {
    slug: "civilization-vii",
    title: "Civilization VII",
    developer: "Firaxis Games",
    releaseDate: "11 Fev 2025",
    platforms: ["PC", "PS5", "Xbox Series X", "Nintendo Switch"],
    summary: "A mais recente entrada da franquia 4X lendária, com um polêmico e inovador sistema de Eras.",
  },
  {
    slug: "manor-lords",
    title: "Manor Lords",
    developer: "Slavic Magic",
    releaseDate: "26 Abr 2024 (EA)",
    platforms: ["PC"],
    summary: "Simulador de gestão medieval com batalhas táticas e solo interativo.",
  },
  {
    slug: "frostpunk-2",
    title: "Frostpunk 2",
    developer: "11 bit studios",
    releaseDate: "20 Set 2024",
    platforms: ["PC", "Xbox Series X"],
    summary: "Gestão de cidade pós-apocalíptica com dilemas políticos e sobrevivência no frio extremo.",
  },
];

export const TRENDING = [
  { id: 5, rank: 1, title: "Os 10 Mods Essenciais para Cities: Skylines II em 2026", views: "92k" },
  { id: 6, rank: 2, title: "Europa Universalis V: Data de Lançamento Confirmada para Março de 2027", views: "74k" },
  { id: 7, rank: 3, title: "Civilization VII recebe nota 8.5 no Metacritic após patch de correção", views: "68k" },
  { id: 8, rank: 4, title: "Manor Lords atinge 2 milhões de cópias vendidas em Early Access", views: "51k" },
  { id: 9, rank: 5, title: "Victoria 4 é oficialmente anunciado pela Paradox Interactive", views: "44k" },
];
